### ISSUE TITLE
上传到 pypi

### ISSUE THREAD

**Issue by Cologler** [yichen0831/opencc-python#3]

**Comment by shuge** [comment]
Please upload it to https://pypi.python.org, thanks.

**Comment by yichen0831** [comment]
Sorry, I have not idea how to do it.

**Comment by Cologler** [comment]
@yichen0831 

first, register a account on https://pypi.python.org

second, create file `.pypirc` in your user dir like `C:\Users\YOUR`, with content:

``` txt
[distutils]
index-servers =
    pypi

[pypi]
username:???????????
password:???????????
```

You already wrote the `setup.py`. 

So you just need to call command `python setup.py register sdist bdist_egg upload`.

**Comment by yichen0831** [comment]
As the package name 'opencc-python' has already been taken, I named my implementation "opencc-python-reimplemented" and uploaded it to pypi.

Now it should be install by issuing:
pip install opencc-python-reimplemented

**Comment by shuge** [comment]
Good job!
